// VocabArena word database — Grades 3–10, three levels each (20 words per level)
// Each entry: { word, definition, example }

const wordDatabase = {

  /* ══════════════ GRADE 3 ══════════════ */
  grade3: {
    novice: [
      { word: "ancient",    definition: "Very old; from a long time ago",                            example: "The ancient oak tree in the park has been there for hundreds of years." },
      { word: "brave",      definition: "Willing to do something difficult or scary",                 example: "The brave firefighter ran into the burning building to save the dog." },
      { word: "calm",       definition: "Quiet and still; not excited or upset",                     example: "The lake was so calm you could see the sky's reflection in the water." },
      { word: "cozy",       definition: "Warm, comfortable, and snug",                               example: "We sat in the cozy cabin while snow fell softly outside." },
      { word: "curious",    definition: "Wanting to know or learn about something",                  example: "The curious puppy sniffed every corner of the new room." },
      { word: "delicate",   definition: "Very fine and easily broken or damaged",                    example: "The butterfly had delicate wings with tiny, colorful patterns." },
      { word: "eager",      definition: "Very excited and ready to do something",                    example: "The students were eager to start the science experiment." },
      { word: "faint",      definition: "Very weak and hard to see or hear",                         example: "We heard a faint knock on the door from the other side of the house." },
      { word: "gentle",     definition: "Soft and careful; not rough",                               example: "She gave the hamster a gentle stroke on its back." },
      { word: "hollow",     definition: "Empty on the inside; having a hole through it",             example: "The owl made its nest inside a hollow tree trunk." },
      { word: "journey",    definition: "A long trip from one place to another",                     example: "The family went on a long journey across three different states." },
      { word: "loyal",      definition: "Always supporting and staying true to someone",             example: "A loyal dog waits by the door every evening for its owner to come home." },
      { word: "mysterious", definition: "Strange and hard to understand or explain",                 example: "A mysterious light glowed in the empty classroom at night." },
      { word: "nimble",     definition: "Moving quickly and easily; light and quick",                example: "The nimble squirrel leaped from branch to branch without slipping." },
      { word: "peculiar",   definition: "Strange or unusual; different from what is normal",         example: "There was a peculiar smell coming from under the kitchen sink." },
      { word: "radiant",    definition: "Sending out a bright, warm light or a warm feeling",        example: "Her radiant smile made everyone in the room feel welcome." },
      { word: "solemn",     definition: "Quiet and serious; not playful",                            example: "Everyone was solemn and still during the memorial ceremony." },
      { word: "swift",      definition: "Moving very fast; quick",                                   example: "The swift cheetah covered the open field in just a few seconds." },
      { word: "timid",      definition: "Shy and easily frightened; lacking confidence",             example: "The timid rabbit hid behind the rock whenever anyone came close." },
      { word: "weary",      definition: "Very tired after a lot of effort",                          example: "After hiking all day, the weary children fell asleep in the car." }
    ],
    sleuth: [
      { word: "blizzard",   definition: "A heavy snowstorm with strong winds",                       example: "The blizzard buried our car in snow overnight." },
      { word: "chorus",     definition: "A group of people singing together; a repeated part of a song", example: "Everyone joined in for the chorus of the birthday song." },
      { word: "clutch",     definition: "To hold something tightly",                                 example: "She clutched her backpack straps as she walked into school on the first day." },
      { word: "distant",    definition: "Far away in place or time",                                 example: "We could see the distant mountains through the airplane window." },
      { word: "dread",      definition: "A strong feeling of fear about something that might happen", example: "He felt dread every time the teacher announced a surprise quiz." },
      { word: "dwell",      definition: "To live in a place; to think about something for a long time", example: "A family of rabbits used to dwell in the garden." },
      { word: "feeble",     definition: "Weak; without much strength or energy",                     example: "The feeble plant drooped because it hadn't been watered in a week." },
      { word: "glimmer",    definition: "A faint or unsteady light",                                 example: "We saw a glimmer of light at the end of the dark cave." },
      { word: "harvest",    definition: "To collect and gather crops from a farm",                   example: "The farmers worked hard to harvest the corn before the storm arrived." },
      { word: "imitate",    definition: "To copy the way someone else acts or speaks",               example: "The parrot could imitate the owner's voice perfectly." },
      { word: "kindle",     definition: "To start a fire; to make a feeling grow stronger",          example: "They used dry leaves to kindle a campfire in the woods." },
      { word: "linger",     definition: "To stay in a place longer than expected",                   example: "The smell of cookies seemed to linger in the kitchen all afternoon." },
      { word: "meadow",     definition: "An open field covered in grass and wildflowers",            example: "The children ran through the meadow chasing butterflies." },
      { word: "moist",      definition: "Slightly wet; damp",                                        example: "She pressed a moist cloth against the sting to reduce the pain." },
      { word: "noble",      definition: "Having good personal qualities; honorable",                 example: "The noble knight always fought to protect people weaker than himself." },
      { word: "preserve",   definition: "To keep something safe from damage or from disappearing",   example: "The museum works hard to preserve old paintings so they last forever." },
      { word: "scurry",     definition: "To move quickly with short, hurried steps",                 example: "The mice would scurry back into their holes when the cat appeared." },
      { word: "shimmer",    definition: "To shine with a soft, wavering light",                      example: "The lake shimmered in the afternoon sun." },
      { word: "tranquil",   definition: "Calm, quiet, and peaceful",                                 example: "The tranquil forest was so quiet we could hear a leaf falling." },
      { word: "tremble",    definition: "To shake slightly, often because of fear or cold",          example: "The small dog trembled with excitement when it heard the leash jingle." }
    ],
    wordsmith: [
      { word: "anticipate", definition: "To expect something and prepare for it ahead of time",      example: "The team tried to anticipate every problem before the big game." },
      { word: "boundary",   definition: "A line that marks the edge or limit of something",          example: "The fence marks the boundary between our yard and the neighbor's." },
      { word: "compassion", definition: "A feeling of caring and wanting to help others who are suffering", example: "Her compassion showed when she shared her lunch with a friend who had forgotten theirs." },
      { word: "demonstrate", definition: "To show how something is done; to prove something",        example: "The teacher will demonstrate the experiment before students try it themselves." },
      { word: "elaborate",  definition: "With many details; to explain something more fully",        example: "He built an elaborate model city out of cardboard boxes." },
      { word: "fascinate",  definition: "To attract and hold someone's complete attention",          example: "The magician's tricks never failed to fascinate the audience." },
      { word: "genuine",    definition: "Real and true; not fake",                                   example: "Her genuine interest in science led her to read every book in the library." },
      { word: "hesitate",   definition: "To pause before doing something because you are unsure",    example: "Don't hesitate to ask for help if you don't understand the question." },
      { word: "illuminate", definition: "To light something up; to make something clear",            example: "The flashlight illuminated the dark path ahead of us." },
      { word: "jealous",    definition: "Feeling upset because someone else has something you want", example: "She was jealous of her brother's new bicycle." },
      { word: "knowledge",  definition: "Facts or information that you have learned",                example: "Reading every day builds up a huge amount of knowledge." },
      { word: "lament",     definition: "To feel or express great sadness about something",          example: "The town laminated the loss of their beloved community garden." },
      { word: "marvel",     definition: "To feel great wonder or surprise at something",             example: "We stood and marveled at the size of the ancient castle." },
      { word: "narrate",    definition: "To tell a story or describe events out loud",               example: "She loves to narrate the adventures she makes up about her stuffed animals." },
      { word: "observe",    definition: "To watch and pay careful attention to something",           example: "Scientists observe the stars through powerful telescopes." },
      { word: "patient",    definition: "Able to wait calmly without complaining",                   example: "You have to be patient when you are learning something new." },
      { word: "remarkable", definition: "Unusual and worthy of attention; impressive",               example: "The young artist showed remarkable skill for her age." },
      { word: "sincere",    definition: "Meaning exactly what you say; honest and genuine",          example: "His sincere apology made his friend feel much better." },
      { word: "transform",  definition: "To completely change the appearance or form of something",  example: "The artists transformed the dull wall into a colorful mural." },
      { word: "vivid",      definition: "Producing clear, strong images; very bright and detailed",  example: "She had such a vivid memory of the trip that she could describe every detail." }
    ]
  },

  /* ══════════════ GRADE 4 ══════════════ */
  grade4: {
    novice: [
      { word: "absorb",     definition: "To take in or soak up something",                           example: "A sponge can absorb a whole cup of water." },
      { word: "beneath",    definition: "Under or below something",                                  example: "The treasure was buried beneath three feet of sand." },
      { word: "certain",    definition: "Sure and confident; without any doubt",                     example: "I am certain that I left my notebook on the desk." },
      { word: "defend",     definition: "To protect someone or something from attack or harm",        example: "The goalkeeper did everything possible to defend the net." },
      { word: "enormous",   definition: "Extremely large; much bigger than normal",                  example: "The enormous elephant was the star of the zoo." },
      { word: "fierce",     definition: "Very intense, powerful, or aggressive",                     example: "The fierce wind knocked several branches off the trees." },
      { word: "gorgeous",   definition: "Very beautiful or attractive",                              example: "The sunset painted gorgeous shades of orange and pink across the sky." },
      { word: "humble",     definition: "Not thinking you are better than other people; modest",     example: "Even after winning the award, she remained humble and thanked her team." },
      { word: "impact",     definition: "A strong effect that something has on a person or situation", example: "Reading every day has a huge impact on how well you write." },
      { word: "keen",       definition: "Very interested in or enthusiastic about something",         example: "He was keen to learn every fact about dinosaurs he could find." },
      { word: "legend",     definition: "A famous story from the past; a very famous person",        example: "The legend of Robin Hood has been told for hundreds of years." },
      { word: "massive",    definition: "Very big and heavy",                                        example: "Movers used a special truck to carry the massive piano." },
      { word: "nourish",    definition: "To provide food and things needed for health and growth",   example: "Fruits and vegetables nourish the body with important vitamins." },
      { word: "obtain",     definition: "To get or gain something, often with some effort",          example: "You need to obtain a library card before borrowing books." },
      { word: "plunge",     definition: "To jump or drop suddenly into something",                   example: "The swimmer took a deep breath and plunged into the cold water." },
      { word: "rugged",     definition: "Having a rough, uneven surface; strong and tough",          example: "The hikers followed a rugged trail through the rocky mountains." },
      { word: "scarce",     definition: "Not enough of something; hard to find",                     example: "During the drought, clean water became scarce in the village." },
      { word: "struggle",   definition: "To try very hard to do something difficult",                example: "She struggled to carry all her books up four flights of stairs." },
      { word: "survive",    definition: "To stay alive, especially after something dangerous",       example: "Some animals can survive in the desert with very little water." },
      { word: "triumph",    definition: "A great success or victory",                               example: "Winning the spelling bee was a triumph for the whole class." }
    ],
    sleuth: [
      { word: "analyze",    definition: "To look at something carefully to understand it better",    example: "Scientists analyze samples of ocean water to check for pollution." },
      { word: "betray",     definition: "To act against someone who trusted you",                    example: "She felt betrayed when her friend shared her secret with others." },
      { word: "clarify",    definition: "To make something easier to understand; to explain clearly", example: "The teacher stopped to clarify the instructions before the test." },
      { word: "deduce",     definition: "To reach a conclusion by thinking carefully about clues",   example: "The detective was able to deduce who had taken the missing cookie." },
      { word: "emphasize",  definition: "To show that something is especially important",            example: "The coach emphasized the importance of practice every day." },
      { word: "gratitude",  definition: "The feeling of being thankful",                             example: "She showed her gratitude by writing a thank-you letter to her teacher." },
      { word: "habitat",    definition: "The natural home or environment of an animal or plant",     example: "A polar bear's habitat is the snowy Arctic." },
      { word: "highlight",  definition: "To draw attention to the most important part of something", example: "The guide used a marker to highlight the most important safety rules." },
      { word: "infer",      definition: "To draw a conclusion from evidence without being told directly", example: "From the muddy boots by the door, she could infer someone had been outside." },
      { word: "justify",    definition: "To give good reasons for doing something; to prove something is right", example: "Can you justify why you need another hour to finish the project?" },
      { word: "logical",    definition: "Following clear, sensible reasoning",                       example: "The most logical solution to getting there faster was to take the shortcut." },
      { word: "motive",     definition: "The reason behind an action",                               example: "The detective looked for a motive before accusing anyone." },
      { word: "navigate",   definition: "To plan and follow a route; to find your way",              example: "Without a map, it was hard to navigate through the unfamiliar city." },
      { word: "obstacle",   definition: "Something that blocks your way or makes progress difficult", example: "The fallen tree was an obstacle on the trail." },
      { word: "precise",    definition: "Exact and accurate, with no errors",                        example: "A surgeon must make very precise cuts during an operation." },
      { word: "reliable",   definition: "Able to be trusted to do what is expected",                 example: "She was the most reliable member of the group because she always kept promises." },
      { word: "significant", definition: "Important or noticeable",                                  example: "Washing your hands regularly has a significant effect on stopping illness." },
      { word: "tackle",     definition: "To deal with a difficult task or problem",                  example: "It's better to tackle a hard homework problem first rather than leave it till last." },
      { word: "uniform",    definition: "The same throughout; not changing",                         example: "The cookies all baked to a uniform golden color." },
      { word: "vivid",      definition: "Producing powerful, lifelike images; very bright and clear", example: "The author used vivid descriptions so readers felt like they were really there." }
    ],
    wordsmith: [
      { word: "allegiance", definition: "Loyalty and commitment to a person, group, or cause",       example: "The soldiers pledged their allegiance to protect their country." },
      { word: "benevolent", definition: "Kind, generous, and wishing well to others",                example: "The benevolent teacher stayed late every day to help students who needed extra support." },
      { word: "circumstance", definition: "The facts and details surrounding an event",              example: "The circumstances of the accident were investigated by the police." },
      { word: "dedicate",   definition: "To give time or energy completely to something",             example: "She dedicated three months of practice to mastering the violin piece." },
      { word: "eloquent",   definition: "Able to speak or write clearly and powerfully",             example: "His eloquent speech convinced the whole school to support the fundraiser." },
      { word: "fluctuate",  definition: "To rise and fall irregularly; to keep changing",            example: "The temperature fluctuated wildly between warm days and cold nights." },
      { word: "hypothesis", definition: "An idea that is proposed as a possible explanation to be tested", example: "Her hypothesis was that plants grow faster with music playing." },
      { word: "illuminate", definition: "To light up; to make something clear and understandable",   example: "The documentary illuminated how much plastic enters the ocean every year." },
      { word: "persevere",  definition: "To keep going despite difficulty or failure",               example: "She persevered through months of training before running her first race." },
      { word: "meticulous", definition: "Very careful and precise, paying attention to every detail", example: "The artist was meticulous about every brush stroke in her painting." },
      { word: "negotiate",  definition: "To discuss something to reach an agreement",                example: "The two teams had to negotiate the rules of the competition before starting." },
      { word: "opposition", definition: "The group or people who disagree and work against something", example: "There was strong opposition to the plan to cut down the old trees." },
      { word: "quest",      definition: "A long search for something important",                     example: "The explorers set off on a quest to find the source of the river." },
      { word: "resilient",  definition: "Able to recover quickly from difficulty",                   example: "Bamboo is resilient; even after a storm bends it flat, it bounces right back." },
      { word: "speculate",  definition: "To form ideas or opinions without knowing all the facts",   example: "Scientists speculate that there may be water beneath the surface of Mars." },
      { word: "tenacious",  definition: "Very determined and not giving up easily",                  example: "The tenacious athlete practiced for years before making it to the national team." },
      { word: "transparent", definition: "Easy to see through; honest and open",                    example: "The glass panel in the beehive was transparent so visitors could watch the bees at work." },
      { word: "undermine",  definition: "To weaken someone's power, confidence, or efforts",         example: "Negative self-talk can undermine your confidence before a big test." },
      { word: "validate",   definition: "To confirm that something is correct or acceptable",        example: "The data from three different studies helped validate the scientist's findings." },
      { word: "wary",       definition: "Careful and alert because you are worried about danger",    example: "Be wary of websites that ask for personal information." }
    ]
  },

  /* ══════════════ GRADE 5 ══════════════ */
  grade5: {
    novice: [
      { word: "abolish",    definition: "To officially put an end to a law or practice",             example: "Many countries worked together to abolish the slave trade." },
      { word: "congested",  definition: "Overfilled; blocked with too much traffic or people",       example: "The highway was congested during the morning rush hour." },
      { word: "debris",     definition: "Broken pieces of something that has been destroyed",        example: "After the storm, the streets were covered in debris from fallen trees." },
      { word: "efficient",  definition: "Working well without wasting time, energy, or materials",   example: "An efficient car uses less fuel per mile than a regular one." },
      { word: "flexible",   definition: "Able to change easily to suit different situations",        example: "A flexible schedule lets you rearrange tasks when unexpected things come up." },
      { word: "generate",   definition: "To produce or create something",                            example: "Solar panels generate electricity from sunlight." },
      { word: "hostile",    definition: "Unfriendly and opposed; showing strong dislike",            example: "The hiker turned back when the weather became hostile." },
      { word: "indicate",   definition: "To point to or show that something is the case",            example: "Dark clouds on the horizon indicate that a storm may be coming." },
      { word: "juvenile",   definition: "Relating to young people; childish in a negative way",     example: "Teasing others is juvenile behavior that should be left behind." },
      { word: "momentum",   definition: "The force or energy that keeps something moving",           example: "The campaign gained so much momentum that everyone wanted to join." },
      { word: "neglect",    definition: "To fail to give proper care or attention to something",     example: "If you neglect watering a plant, it will eventually wilt and die." },
      { word: "obstacle",   definition: "Something that makes it hard to move forward or succeed",   example: "A lack of internet access is a real obstacle for students learning online." },
      { word: "peculiar",   definition: "Strange or unusual; not what you would normally expect",    example: "The scientist noticed a peculiar pattern in the data that no one could explain." },
      { word: "regardless", definition: "Without being affected by; in spite of",                   example: "She went to school regardless of the heavy rain." },
      { word: "skeptical",  definition: "Having doubts; not easily convinced",                       example: "He was skeptical about the ad's claim that the product worked in one minute." },
      { word: "transmit",   definition: "To send information, energy, or signals from one place to another", example: "Radios transmit music and voices through invisible waves." },
      { word: "unique",     definition: "Being the only one of its kind; unlike anything else",     example: "Every snowflake has a unique crystal structure." },
      { word: "venture",    definition: "To go somewhere or do something that involves some risk",   example: "The hikers decided to venture deeper into the cave with only one flashlight." },
      { word: "wither",     definition: "To dry up and lose strength; to shrink and fade",          example: "The flowers began to wither after three days without water." },
      { word: "yearn",      definition: "To feel a strong and deep desire for something",            example: "After months away, he yearned to see his family again." }
    ],
    sleuth: [
      { word: "adversary",  definition: "An opponent or enemy",                                      example: "In the story, the hero must outsmart his adversary to save the kingdom." },
      { word: "contradict", definition: "To say the opposite of what someone else has said",         example: "The new evidence seemed to contradict the original conclusion." },
      { word: "diligent",   definition: "Hardworking and careful, especially over a long time",      example: "Diligent students review their notes every evening after class." },
      { word: "elaborate",  definition: "To give more details or explain something further",         example: "Can you elaborate on why you think your plan will work?" },
      { word: "flourish",   definition: "To grow well and be healthy; to be very successful",        example: "With daily sunlight and water, the garden began to flourish." },
      { word: "gratify",    definition: "To please or satisfy someone",                              example: "It gratified her to know her hard work had helped someone in need." },
      { word: "illustrious", definition: "Well-known and highly respected because of past achievements", example: "The museum honored the illustrious scientist who discovered the cure." },
      { word: "jeopardize", definition: "To put something at risk of being harmed or lost",          example: "Skipping practice every week could jeopardize your place on the team." },
      { word: "lackluster", definition: "Not exciting or impressive; dull",                          example: "The team gave a lackluster performance in the first half of the game." },
      { word: "magnify",    definition: "To make something appear larger; to increase the intensity of something", example: "Stress can magnify small problems into big ones." },
      { word: "nullify",    definition: "To make something lose its effect or be invalid",           example: "The broken seal nullified the agreement between the two companies." },
      { word: "ominous",    definition: "Giving the impression that something bad is about to happen", example: "The ominous silence in the house made her uneasy." },
      { word: "perplex",    definition: "To confuse someone completely; to puzzle",                  example: "The riddle perplexed even the smartest student in the class." },
      { word: "refute",     definition: "To prove that a claim or argument is wrong",                example: "She used three pieces of evidence to refute the opposing argument." },
      { word: "sustain",    definition: "To keep something going over time; to support",             example: "A healthy diet helps sustain your energy throughout the day." },
      { word: "tyranny",    definition: "Cruel and unfair use of power over others",                 example: "The villagers rose up against the king's tyranny." },
      { word: "validate",   definition: "To prove or confirm that something is correct or real",     example: "A doctor's signature is needed to validate the medical form." },
      { word: "wary",       definition: "Cautious and watchful, especially about danger",            example: "Be wary of messages from people you don't know online." },
      { word: "yearning",   definition: "A strong feeling of wanting something you cannot easily have", example: "She felt a deep yearning to return to the town where she grew up." },
      { word: "zealous",    definition: "Showing great energy and enthusiasm for a cause",           example: "The zealous volunteers arrived an hour early to set up the event." }
    ],
    wordsmith: [
      { word: "ambiguous",  definition: "Having more than one possible meaning; not clear",          example: "The ending of the story was ambiguous — readers were unsure what really happened." },
      { word: "brevity",    definition: "Using few words; expressing something in a short time",     example: "He was praised for the brevity of his speech, which got the point across in minutes." },
      { word: "consequence", definition: "A result or effect of an action",                          example: "Acting without thinking often leads to consequences you did not expect." },
      { word: "dilemma",    definition: "A difficult choice between two options that are both hard", example: "She faced a dilemma: stay at the party or leave to finish her project." },
      { word: "empathy",    definition: "The ability to understand and share someone else's feelings", example: "Good doctors show empathy by listening carefully to their patients." },
      { word: "fortitude",  definition: "Courage and strength to deal with pain or difficulty",     example: "It took great fortitude to keep training after the injury." },
      { word: "grapple",    definition: "To struggle with a difficult problem",                      example: "The committee grappled with the question of how to fairly divide the budget." },
      { word: "hubris",     definition: "Excessive pride or overconfidence that often leads to failure", example: "His hubris made him think he didn't need to study, and he failed the test." },
      { word: "infer",      definition: "To reach a conclusion based on evidence, not direct statement", example: "From the torn wrapping paper, she could infer that someone had already opened the gift." },
      { word: "kinship",    definition: "A close connection or relationship",                        example: "She felt a strong kinship with others who had grown up in the same neighborhood." },
      { word: "lucid",      definition: "Clear and easy to understand; mentally alert",              example: "Even on a complex topic, he gave a lucid and easy-to-follow explanation." },
      { word: "meticulous", definition: "Extremely careful about details; very precise",             example: "She was meticulous in her research, checking every single source twice." },
      { word: "nomadic",    definition: "Moving from place to place without a permanent home",       example: "Many early human groups lived nomadic lives, following animal herds." },
      { word: "obstinate",  definition: "Refusing to change your mind even when you should; stubborn", example: "He was so obstinate that even proof didn't change his opinion." },
      { word: "persevere",  definition: "To keep trying despite difficulties or setbacks",           example: "She persevered through four failed attempts before finally passing her driving test." },
      { word: "resilient",  definition: "Able to quickly recover from hardship or failure",          example: "Resilient communities rebuild quickly after natural disasters." },
      { word: "subordinate", definition: "Lower in rank or importance; to treat as less important",  example: "A good leader doesn't make team members feel subordinate or unheard." },
      { word: "tenacious",  definition: "Holding firmly to something; not giving up",               example: "Her tenacious grip on the rope kept her from falling." },
      { word: "undermine",  definition: "To slowly weaken or damage something from within",         example: "Rumors can undermine the trust that holds a team together." },
      { word: "vigilant",   definition: "Keeping careful watch for possible danger",                 example: "You need to be vigilant about your online privacy settings." }
    ]
  },

  /* ══════════════ GRADE 6 ══════════════ */
  grade6: {
    novice: [
      { word: "ambitious",  definition: "Having a strong desire to succeed or achieve something great", example: "She was ambitious enough to apply for a spot on the national debate team." },
      { word: "condemn",    definition: "To say strongly that something is wrong or unacceptable",   example: "World leaders were quick to condemn the unprovoked attack." },
      { word: "dispute",    definition: "A disagreement or argument, especially a formal one",       example: "The two countries settled their border dispute through peaceful talks." },
      { word: "enforce",    definition: "To make sure a law or rule is obeyed",                     example: "The referee's job is to enforce the rules of the game fairly." },
      { word: "flourish",   definition: "To thrive and grow in a healthy or successful way",         example: "The new business began to flourish once it found the right customers." },
      { word: "impulsive",  definition: "Acting quickly without thinking carefully first",           example: "Her impulsive decision to dye her hair purple surprised everyone." },
      { word: "intricate",  definition: "Very complex and detailed",                                 example: "The intricate pattern on the fabric took weeks to weave by hand." },
      { word: "justify",    definition: "To provide good reasons to show something is right",        example: "How can you justify staying up until midnight on a school night?" },
      { word: "leverage",   definition: "Using something to your advantage to achieve a goal",       example: "She used her language skills as leverage to get a better job." },
      { word: "mitigate",   definition: "To make something less severe or harmful",                  example: "Wearing sunscreen helps mitigate the risk of sunburn." },
      { word: "notorious",  definition: "Famous for something bad",                                  example: "The road was notorious for flooding every time it rained heavily." },
      { word: "optimum",    definition: "The most favorable or best possible condition",             example: "Eight hours of sleep is considered the optimum amount for a teenager." },
      { word: "plausible",  definition: "Seeming reasonable and likely to be true",                  example: "The alibi wasn't completely convincing, but it was at least plausible." },
      { word: "reconcile",  definition: "To make two things compatible; to resolve a disagreement",  example: "The friends reconciled after an honest conversation about their misunderstanding." },
      { word: "scrutiny",   definition: "Very careful and detailed examination or observation",      example: "The contract was placed under intense scrutiny before anyone signed it." },
      { word: "temperate",  definition: "Mild in temperature; moderate and controlled in behavior",  example: "The region has a temperate climate, with warm summers and cool winters." },
      { word: "undermine",  definition: "To gradually weaken or damage something",                   example: "Poor preparation can undermine even the most talented speaker's performance." },
      { word: "validate",   definition: "To confirm that something is correct, real, or acceptable", example: "Research is needed to validate the new treatment before it can be used on patients." },
      { word: "vague",      definition: "Not clear or specific; uncertain",                          example: "His instructions were so vague that nobody knew where to go." },
      { word: "wholesome",  definition: "Promoting health and good values; morally good",            example: "The book offered a wholesome message about friendship and kindness." }
    ],
    sleuth: [
      { word: "adversity",  definition: "Difficult or unpleasant circumstances",                     example: "She showed remarkable strength in the face of great adversity." },
      { word: "contemplate", definition: "To think deeply and carefully about something",             example: "He stood at the edge of the cliff, contemplating his next move." },
      { word: "desolate",   definition: "Empty of people; causing a feeling of sadness and loneliness", example: "The abandoned town looked desolate, with broken windows and overgrown roads." },
      { word: "evocative",  definition: "Bringing strong images, memories, or feelings to mind",     example: "The photograph was evocative of simpler, happier times." },
      { word: "formidable", definition: "Inspiring fear or respect because of impressive power or size", example: "She was a formidable chess player who had never lost a tournament." },
      { word: "gratuitous", definition: "Uncalled for; unnecessary and without good reason",          example: "The film was criticized for its gratuitous use of violence." },
      { word: "hierarchy",  definition: "A system in which people or things are ranked by importance or power", example: "In some companies, the hierarchy makes it hard for junior employees to be heard." },
      { word: "impeccable", definition: "Flawless; perfect, without any faults",                    example: "Her impeccable grammar made her essays a pleasure to read." },
      { word: "jeopardize", definition: "To put at risk; to endanger",                               example: "Skipping meals will jeopardize your energy and concentration." },
      { word: "lament",     definition: "To feel or express great sorrow about something",           example: "He lamented the fact that the old cinema had been demolished." },
      { word: "mundane",    definition: "Ordinary and not interesting; lacking excitement",          example: "Folding laundry is a mundane task that most people avoid." },
      { word: "nonchalant", definition: "Appearing calm and not worried about anything",             example: "She was nonchalant about losing the match, as if it didn't bother her at all." },
      { word: "obscure",    definition: "Not well-known; difficult to understand",                   example: "He found an obscure book about medieval maps in the back of the library." },
      { word: "paradox",    definition: "A situation or statement that seems contradictory but may be true", example: "The paradox of being busy all the time yet never achieving anything puzzled her." },
      { word: "relentless", definition: "Continuing without stopping; refusing to give up",          example: "The team's relentless effort in the final quarter led to victory." },
      { word: "substantial", definition: "Large in size, amount, or importance",                     example: "The fundraiser raised a substantial amount of money for the school library." },
      { word: "trivial",    definition: "Of very little importance; insignificant",                  example: "Don't waste energy arguing over trivial things." },
      { word: "ulterior",   definition: "Hidden; involving a secret purpose or motive",              example: "She suspected he had an ulterior motive for offering to help." },
      { word: "verbose",    definition: "Using more words than needed; long-winded",                 example: "His verbose reply took ten minutes to say what could have been said in one." },
      { word: "wistful",    definition: "Feeling a gentle sadness mixed with longing",               example: "She gave a wistful smile when she found her old childhood drawings." }
    ],
    wordsmith: [
      { word: "allegory",   definition: "A story in which characters and events symbolize deeper meanings", example: "George Orwell's Animal Farm is an allegory about political power and corruption." },
      { word: "bureaucracy", definition: "A system with complex rules and processes, often causing delays", example: "Getting a passport requires going through a lot of bureaucracy." },
      { word: "connotation", definition: "The feeling or idea associated with a word beyond its literal meaning", example: "The word 'home' has a warm, safe connotation that 'house' does not." },
      { word: "deference",  definition: "Respectful submission to another person's opinion or wishes",  example: "In deference to her elders, she waited until they had spoken before sharing her view." },
      { word: "eloquence",  definition: "The ability to speak or write clearly, beautifully, and persuasively", example: "The lawyer's eloquence in the courtroom left the jury deeply moved." },
      { word: "fallacy",    definition: "A false belief or an error in reasoning",                    example: "It's a fallacy to think that expensive things are always better quality." },
      { word: "gregarious", definition: "Enjoying the company of others; sociable",                  example: "Being gregarious comes naturally to her — she lights up at every party." },
      { word: "insinuate",  definition: "To suggest something in an indirect way, often unpleasantly", example: "He insinuated that she hadn't done her fair share of the work." },
      { word: "juxtapose",  definition: "To place two things side by side to highlight their differences", example: "The director juxtaposed scenes of luxury and poverty to make a social point." },
      { word: "loquacious", definition: "Talking a great deal; very talkative",                      example: "The loquacious host kept the conversation going for three hours." },
      { word: "melancholy", definition: "A deep, lasting feeling of sadness",                        example: "A sense of melancholy settled over the town when the school closed for good." },
      { word: "nuance",     definition: "A subtle difference in meaning, tone, or feeling",           example: "Her nuanced reading of the poem captured meanings others had missed." },
      { word: "oblivious",  definition: "Not aware of what is happening around you",                  example: "He was so absorbed in his book that he was oblivious to the noise around him." },
      { word: "pragmatic",  definition: "Dealing with problems in a practical, sensible way",         example: "Her pragmatic approach to the budget saved the project from collapse." },
      { word: "recalcitrant", definition: "Stubbornly refusing to cooperate",                        example: "The recalcitrant student refused to do the assignment no matter what the teacher said." },
      { word: "skepticism", definition: "A doubtful attitude; not accepting claims without evidence", example: "Healthy skepticism leads scientists to test ideas before accepting them as fact." },
      { word: "tangential", definition: "Slightly connected to a topic but not directly relevant",   example: "His comment about music was interesting but tangential to our discussion of history." },
      { word: "ubiquitous", definition: "Seeming to be everywhere at the same time",                 example: "Smartphones have become ubiquitous — almost everyone carries one." },
      { word: "visceral",   definition: "Coming from deep instinct rather than reason; gut-level",   example: "Her visceral reaction to the news was to burst into tears before she could think." },
      { word: "zeitgeist",  definition: "The general mood, ideas, or spirit of a particular period in history", example: "Social media has become a major part of today's zeitgeist." }
    ]
  },

  /* ══════════════ GRADE 7 ══════════════ */
  grade7: {
    novice: [
      { word: "advocate",   definition: "To publicly support or argue for a cause; a person who does this", example: "She advocates strongly for better school lunches." },
      { word: "benign",     definition: "Gentle and not causing harm; not dangerous",                 example: "The doctor confirmed that the growth was benign and harmless." },
      { word: "catalyst",   definition: "Something that causes change or speeds up a process",        example: "His speech was a catalyst that inspired hundreds of people to volunteer." },
      { word: "discern",    definition: "To recognize or understand something that is not obvious",   example: "It takes experience to discern genuine compliments from flattery." },
      { word: "emulate",    definition: "To try to equal or copy someone admired",                   example: "Young athletes often emulate the style of their sports heroes." },
      { word: "fervent",    definition: "Having or showing great intensity of feeling",              example: "She was a fervent supporter of environmental conservation." },
      { word: "grapple",    definition: "To struggle with something difficult",                      example: "Many students grapple with time management in their first year of high school." },
      { word: "hubris",     definition: "Excessive pride that leads to downfall",                    example: "The character's hubris — his belief he was invincible — caused his defeat." },
      { word: "implicit",   definition: "Suggested or understood without being directly stated",     example: "There was an implicit expectation that everyone would contribute equally." },
      { word: "kindle",     definition: "To arouse or inspire a feeling or interest",               example: "A great teacher can kindle a love of learning that lasts a lifetime." },
      { word: "mediocre",   definition: "Of only average quality; not very good",                    example: "A mediocre performance from the team left the coach disappointed." },
      { word: "negate",     definition: "To make ineffective or invalid; to deny",                   example: "One careless mistake can negate hours of careful preparation." },
      { word: "ominous",    definition: "Giving a strong feeling that something bad is about to happen", example: "The dark, ominous clouds warned of a coming storm." },
      { word: "perpetuate", definition: "To cause something to continue indefinitely",               example: "Repeating stereotypes only perpetuates harmful ideas." },
      { word: "quell",      definition: "To put an end to; to calm or suppress",                    example: "The counselor's kind words helped quell the student's anxiety." },
      { word: "rhetoric",   definition: "Language used to persuade; impressive but sometimes empty speech", example: "Politicians often use rhetoric to win support without giving real plans." },
      { word: "scrutinize", definition: "To examine very closely and critically",                    example: "Detectives scrutinized every detail of the scene before drawing conclusions." },
      { word: "tenacious",  definition: "Holding on firmly; very determined",                       example: "Her tenacious grip on her goals saw her through years of setbacks." },
      { word: "trepidation", definition: "A feeling of fear or anxiety about what might happen",    example: "She approached the stage with some trepidation but quickly gained confidence." },
      { word: "wary",       definition: "Feeling cautious because of possible danger",               example: "He was wary of making promises he might not be able to keep." }
    ],
    sleuth: [
      { word: "abdicate",   definition: "To give up a powerful position or responsibility",          example: "When the leader abdicated responsibility, the team fell into confusion." },
      { word: "brevity",    definition: "Conciseness; saying what's needed in as few words as possible", example: "The director admired the script's brevity — it was tight and punchy." },
      { word: "capitulate", definition: "To stop resisting and give in to demands",                  example: "After days of negotiation, the company finally capitulated to the workers' demands." },
      { word: "discordant", definition: "Lacking agreement; producing harsh, jarring sounds or ideas", example: "The discordant voices in the argument made it impossible to find common ground." },
      { word: "equivocate", definition: "To use vague or ambiguous language to avoid commitment",    example: "She equivocated when asked for her opinion, never giving a clear answer." },
      { word: "formidable", definition: "Inspiring great respect or even fear because of power",     example: "The defense team faced a formidable legal opponent with a perfect record." },
      { word: "garrulous",  definition: "Excessively talkative, especially about trivial things",   example: "His garrulous nature made meetings run well past their scheduled time." },
      { word: "hypocrite",  definition: "Someone who says one thing but does another",               example: "It's hypocritical to preach patience while losing your temper every day." },
      { word: "impervious", definition: "Unable to be affected by something",                        example: "She seemed impervious to criticism and never changed her approach." },
      { word: "juxtapose",  definition: "To place two contrasting things together to emphasize their differences", example: "The director juxtaposed scenes of joy and grief throughout the film." },
      { word: "laconic",    definition: "Using very few words; brief and to the point",              example: "His laconic reply was a single word: 'No.'" },
      { word: "mendacious", definition: "Not telling the truth; lying",                              example: "The mendacious witness changed his story three times on the stand." },
      { word: "nuance",     definition: "A very slight difference in meaning, color, or feeling",    example: "Understanding the nuances of tone is essential to reading between the lines." },
      { word: "ostracize",  definition: "To deliberately exclude someone from a group",              example: "The character is ostracized by his classmates for being different." },
      { word: "preclude",   definition: "To prevent something from happening; to rule out",          example: "Bad weather may preclude the possibility of an outdoor ceremony." },
      { word: "querulous",  definition: "Complaining in an irritable or whiny way",                 example: "The querulous passenger complained about every single aspect of the flight." },
      { word: "recant",     definition: "To take back a previous statement or belief publicly",      example: "Under pressure, the witness recanted his earlier testimony." },
      { word: "sycophant",  definition: "A person who flatters powerful people in an insincere way to gain advantage", example: "Every leader attracts sycophants who agree with everything said." },
      { word: "turbulent",  definition: "Characterized by conflict, disorder, or instability",       example: "The country went through a turbulent decade of political unrest." },
      { word: "vacuous",    definition: "Lacking thought, intelligence, or meaning",                 example: "The celebrity's vacuous comments offered nothing of value to the conversation." }
    ],
    wordsmith: [
      { word: "absolution", definition: "Formal forgiveness, especially for wrongdoing",             example: "The character sought absolution for the harm he had caused years earlier." },
      { word: "belligerent", definition: "Aggressively hostile and likely to fight",                 example: "The belligerent crowd had to be dispersed by security." },
      { word: "circumvent", definition: "To find a way around a rule or obstacle",                   example: "He tried to circumvent the rules by submitting work under a different name." },
      { word: "diatribe",   definition: "A long, angry speech criticizing someone or something",     example: "Her diatribe against the administration went on for a full hour." },
      { word: "ephemeral",  definition: "Lasting for only a short time",                             example: "Internet trends are ephemeral — viral today, forgotten tomorrow." },
      { word: "fallacious", definition: "Based on incorrect reasoning; misleading",                  example: "Her argument was fallacious because it relied on a false assumption." },
      { word: "hegemony",   definition: "Dominant power or influence over others",                   example: "The company sought hegemony in the global streaming market." },
      { word: "imperious",  definition: "Expecting obedience; arrogantly bossy",                    example: "Her imperious tone made colleagues feel they had no choice but to comply." },
      { word: "laudatory",  definition: "Expressing praise",                                         example: "The review was laudatory, calling it the best novel of the decade." },
      { word: "mendacity",  definition: "The practice of being untruthful; habitual lying",          example: "His mendacity was exposed when three different witnesses contradicted his story." },
      { word: "nihilism",   definition: "The belief that life has no meaning or purpose",            example: "The character's nihilism left him unable to care about anything." },
      { word: "obsequious", definition: "Excessively eager to please or obey; fawning",             example: "The obsequious assistant agreed with everything the boss said." },
      { word: "perfidious", definition: "Guilty of betrayal; deceitful and untrustworthy",          example: "His perfidious act of leaking secrets destroyed his reputation." },
      { word: "quixotic",   definition: "Unrealistically idealistic; pursuing impossible goals",     example: "His quixotic dream of single-handedly cleaning the ocean seemed far-fetched." },
      { word: "recalcitrant", definition: "Stubbornly resisting authority or control",               example: "The recalcitrant prisoner refused every attempt at rehabilitation." },
      { word: "sophistry",  definition: "Clever but misleading arguments",                           example: "The debate was full of sophistry — arguments that sounded good but didn't hold up." },
      { word: "truculent",  definition: "Quick to argue or fight; aggressively defiant",             example: "The truculent player argued every call the referee made." },
      { word: "vacuous",    definition: "Having or showing a lack of thought or intelligence",       example: "Critics dismissed the reality show as vacuous entertainment with no value." },
      { word: "vitriolic",  definition: "Full of bitter, sharp, and cruel criticism",               example: "The vitriolic review attacked not just the book but the author personally." },
      { word: "zealotry",   definition: "Extreme and uncompromising devotion to a cause",            example: "His zealotry for his political views made it impossible to have a balanced debate." }
    ]
  },

  /* ══════════════ GRADE 8 ══════════════ */
  grade8: {
    novice: [
      { word: "aberrant",   definition: "Departing from what is normal or expected",                 example: "The scientist flagged the aberrant results as a sign that the experiment had gone wrong." },
      { word: "circumspect", definition: "Wary and cautious; considering all circumstances and consequences", example: "She was circumspect about sharing personal information online." },
      { word: "denigrate",  definition: "To unfairly criticize or damage the reputation of",         example: "It's wrong to denigrate people for making mistakes they've already learned from." },
      { word: "elucidate",  definition: "To make something clear; to explain in detail",             example: "The professor paused to elucidate the most confusing section of the theory." },
      { word: "fastidious", definition: "Very attentive to accuracy and detail; hard to please",    example: "She was fastidious about formatting — every comma had to be in exactly the right place." },
      { word: "gregarious", definition: "Sociable and enjoying the company of others",              example: "His gregarious personality made him a natural fit for a career in public relations." },
      { word: "idiosyncratic", definition: "Peculiar or individual to a particular person",         example: "Her idiosyncratic speaking style, full of unusual phrases, made her stand out." },
      { word: "jocular",    definition: "Fond of joking; humorous",                                  example: "His jocular remarks lightened the mood during the tense meeting." },
      { word: "kinetic",    definition: "Relating to motion; full of active energy",                 example: "The kinetic sculpture shifted and spun with every breath of wind." },
      { word: "lethargic",  definition: "Lacking energy and enthusiasm; sluggish",                  example: "After the long journey, the whole team felt lethargic and struggled to concentrate." },
      { word: "meticulous", definition: "Showing great care about every detail",                     example: "The archivist was meticulous in cataloguing every item in the collection." },
      { word: "nefarious",  definition: "Wicked and criminal",                                       example: "The villain's nefarious scheme was eventually uncovered by the detective." },
      { word: "oblique",    definition: "Not direct; expressing something in an indirect way",       example: "Her oblique response to the question left everyone unsure of her true opinion." },
      { word: "pernicious", definition: "Causing serious harm in a gradual and subtle way",         example: "The pernicious effects of misinformation can take years to undo." },
      { word: "querulous",  definition: "Petulantly complaining or whining",                        example: "The querulous toddler refused every meal that was offered to him." },
      { word: "reticent",   definition: "Not willing to share thoughts or feelings; reserved",       example: "He was reticent about his past and gave only vague answers." },
      { word: "stoic",      definition: "Enduring hardship without showing feelings or complaining", example: "Despite the pain, she remained stoic throughout the long recovery." },
      { word: "tenacious",  definition: "Very determined; not giving up despite difficulty",         example: "Her tenacious pursuit of justice eventually led to a landmark legal ruling." },
      { word: "wistful",    definition: "Having or expressing a longing for something past",         example: "He gave a wistful sigh as he passed his old school." },
      { word: "zenith",     definition: "The highest point; the peak of achievement",                example: "She reached the zenith of her career when she was appointed to lead the organization." }
    ],
    sleuth: [
      { word: "acrimony",   definition: "Bitterness and ill feeling in speech or behavior",          example: "The divorce was marked by such acrimony that the two sides refused to speak." },
      { word: "bellicose",  definition: "Aggressive; eager to argue or fight",                       example: "His bellicose tweets made it clear he was looking for a public argument." },
      { word: "capricious", definition: "Changing mood or mind suddenly and unexpectedly",           example: "The capricious weather changed from sunshine to hail in minutes." },
      { word: "didactic",   definition: "Intended to teach a moral lesson; overly instructive",      example: "Some readers find the novel too didactic — it feels more like a lecture than a story." },
      { word: "endemic",    definition: "Regularly found in a particular area or group",             example: "Corruption was endemic in the region and had been for generations." },
      { word: "facetious",  definition: "Treating serious issues with inappropriate humor",          example: "His facetious comment during the crisis briefing was poorly received." },
      { word: "hedonistic", definition: "Devoted to seeking pleasure and self-indulgence",           example: "His hedonistic lifestyle eventually caught up with his health." },
      { word: "incendiary", definition: "Designed to cause controversy; tending to inflame passions", example: "The incendiary speech divided the community rather than uniting it." },
      { word: "laconic",    definition: "Using very few words; brief and concise",                   example: "Her laconic emails contained exactly the information needed — nothing more." },
      { word: "malevolent", definition: "Having or showing a wish to harm others; evil",             example: "The malevolent character took pleasure in other people's misfortunes." },
      { word: "nonchalant", definition: "Feeling or appearing casually calm, especially when it's inappropriate", example: "His nonchalant shrug after failing the exam alarmed his teachers." },
      { word: "obdurate",   definition: "Stubbornly refusing to change one's opinion or action",    example: "She remained obdurate in her refusal to apologize despite clear evidence." },
      { word: "pernicious", definition: "Causing serious harm, especially gradually",               example: "The pernicious habit of skipping sleep had long-term effects on her health." },
      { word: "rancorous",  definition: "Bitter and resentful",                                      example: "The rancorous debate produced no solutions, only deepened divisions." },
      { word: "sanguine",   definition: "Optimistic, especially in a difficult situation",           example: "Despite the setbacks, she remained sanguine about the project's chances." },
      { word: "truculent",  definition: "Eager and quick to argue or fight",                         example: "The truculent negotiator rejected every compromise before it was fully explained." },
      { word: "unctuous",   definition: "Excessively flattering in a way that seems insincere",     example: "The unctuous salesman made everyone uncomfortable with his hollow compliments." },
      { word: "vociferous", definition: "Expressing views loudly and forcefully",                    example: "Vociferous protesters gathered outside the building throughout the night." },
      { word: "zealous",    definition: "Showing enthusiastic and strong support for a cause",       example: "The zealous campaigners knocked on thousands of doors before the election." },
      { word: "zeitgeist",  definition: "The defining mood or spirit of a particular era",           example: "The film perfectly captures the zeitgeist of the anxious early 2000s." }
    ],
    wordsmith: [
      { word: "anachronism", definition: "Something that belongs to a different time period and is out of place in the present", example: "A knight in shining armor walking through a city is a classic anachronism." },
      { word: "byzantine",  definition: "Excessively complicated; involving intricate politics",     example: "The tax code had become so byzantine that even accountants struggled with it." },
      { word: "colloquial", definition: "Used in ordinary informal conversation rather than formal writing", example: "Contractions like 'don't' and 'can't' are colloquial forms used in casual speech." },
      { word: "demagogue",  definition: "A political leader who wins support by appealing to fears and prejudices", example: "History warns us that a charismatic demagogue can lead entire nations astray." },
      { word: "equivocal",  definition: "Open to more than one interpretation; deliberately vague",  example: "His equivocal response left investors unsure whether to proceed." },
      { word: "heretical",  definition: "Contrary to accepted beliefs; unorthodox",                  example: "In the 17th century, the idea that the Earth orbited the Sun was considered heretical." },
      { word: "iconoclast", definition: "A person who attacks cherished beliefs or institutions",    example: "The iconoclast artist deliberately broke every convention of classical painting." },
      { word: "machiavellian", definition: "Cunning, scheming, and unscrupulous in pursuing political goals", example: "His Machiavellian maneuvers within the party left few allies and many enemies." },
      { word: "nihilistic", definition: "Rejecting all religious and moral principles; believing life is meaningless", example: "The character's nihilistic worldview made it impossible for him to act on anything." },
      { word: "obstreperous", definition: "Noisy and difficult to control",                          example: "The obstreperous crowd made it impossible for the speaker to be heard." },
      { word: "pedantic",   definition: "Overly concerned with minor details or rules; showing off knowledge", example: "His pedantic corrections of everyone's grammar made the conversation exhausting." },
      { word: "quixotic",   definition: "Exceedingly idealistic and impractical",                    example: "His quixotic plan to solve world hunger with a single invention impressed no one." },
      { word: "recalcitrant", definition: "Uncooperative; stubbornly resistant to authority",        example: "The recalcitrant executive refused every request from the regulator." },
      { word: "sycophant",  definition: "A person who uses flattery to gain favor",                  example: "Surrounded by sycophants, the CEO received no honest feedback." },
      { word: "truculent",  definition: "Eager to argue; aggressively defiant",                      example: "The truculent star player was fined for arguing with officials." },
      { word: "xenophobic", definition: "Having an irrational fear or hatred of foreigners",         example: "Xenophobic attitudes increase during times of economic uncertainty." },
      { word: "zealotry",   definition: "Extreme and uncritical devotion to a cause",               example: "The zealotry of the faction's members made moderate reform impossible." },
      { word: "vitriol",    definition: "Harsh and bitter criticism",                               example: "The editorial was full of vitriol, attacking every aspect of the policy." },
      { word: "solipsism",  definition: "The idea that only one's own mind is certain to exist; extreme self-absorption", example: "His solipsism made it impossible for him to understand anyone else's point of view." },
      { word: "polemic",    definition: "A strong verbal or written attack on a specific opinion or person", example: "The pamphlet was a polemic against the proposed development of the nature reserve." }
    ]
  },

  /* ══════════════ GRADE 9 ══════════════ */
  grade9: {
    novice: [
      { word: "abstruse",   definition: "Difficult to understand; obscure",                          example: "The philosopher's abstruse arguments required the students to read each paragraph twice." },
      { word: "cogent",     definition: "Clear, logical, and convincing",                            example: "She made a cogent argument that changed several members' votes." },
      { word: "dialectic",  definition: "A method of argument that arrives at truth through opposing views", example: "The dialectic between the two theories eventually produced a more nuanced understanding." },
      { word: "empirical",  definition: "Based on observation or experience rather than theory",     example: "The researchers needed empirical data from real trials before drawing any conclusions." },
      { word: "fortuitous", definition: "Happening by chance, especially in a lucky way",            example: "A fortuitous meeting at a conference led to a career-changing opportunity." },
      { word: "hegemony",   definition: "Leadership or dominance, especially by one country or group over others", example: "The novel explores a world where one empire's hegemony has suppressed all others." },
      { word: "inchoate",   definition: "Just beginning and not fully formed or developed",          example: "She had only an inchoate idea for the project but enough to pitch it to the team." },
      { word: "lachrymose", definition: "Tearful; tending to cry a lot",                             example: "The lachrymose film left half the audience reaching for tissues." },
      { word: "mendacious", definition: "Not telling the truth; lying",                              example: "His mendacious account of events was contradicted by video evidence." },
      { word: "nefarious",  definition: "Wicked or criminal",                                        example: "The investigation revealed the full extent of the organization's nefarious activities." },
      { word: "obsequious", definition: "Servile and excessively eager to please",                  example: "The obsequious assistant laughed at every joke the director made, even the bad ones." },
      { word: "perfidious", definition: "Guilty of betrayal or treachery",                          example: "The perfidious ally signed a secret treaty with the opposing side." },
      { word: "querulous",  definition: "Complaining in a fretful, petulant way",                   example: "The querulous critic found fault with every performance that season." },
      { word: "reticent",   definition: "Reluctant to speak or share information",                  example: "The witness was reticent and had to be prompted repeatedly for each answer." },
      { word: "sanguine",   definition: "Optimistic, particularly when others are not",              example: "She remained sanguine about the project's chances despite three consecutive setbacks." },
      { word: "tenacious",  definition: "Holding fast; persisting over a long time",                example: "The tenacious reporter refused to drop the story even when pressure was applied." },
      { word: "truculent",  definition: "Aggressively defiant; eager to quarrel",                   example: "His truculent refusal to cooperate stalled the entire investigation." },
      { word: "umbrage",    definition: "Offense or annoyance",                                      example: "She took umbrage at the suggestion that she hadn't worked hard enough." },
      { word: "vestige",    definition: "A trace or remnant of something that is disappearing or no longer exists", example: "The ruins were the last vestige of a once-great civilization." },
      { word: "vitiate",    definition: "To impair the quality or effectiveness of something",       example: "A single missing clause could vitiate the entire legal contract." }
    ],
    sleuth: [
      { word: "acrimonious", definition: "Angry and bitter, especially in a dispute",               example: "The acrimonious breakup of the band was played out in public." },
      { word: "bellwether", definition: "A leader or indicator of trends; the one that leads the flock", example: "Silicon Valley remains the bellwether for the global tech industry." },
      { word: "capricious", definition: "Given to sudden and unaccountable changes of mood",         example: "The capricious investor pulled funding without warning, shocking the startup." },
      { word: "deracinate", definition: "To uproot from one's culture or environment",               example: "Many immigrants feel deracinated when they move to a country with a different culture." },
      { word: "ephemeral",  definition: "Lasting a very short time",                                 example: "The ephemeral nature of social media fame rarely translates into real influence." },
      { word: "garrulous",  definition: "Excessively talkative",                                     example: "Her garrulous neighbor talked for forty minutes about the weather." },
      { word: "heretical",  definition: "Going against accepted or established doctrine",            example: "His heretical position on climate change made him unpopular at scientific conferences." },
      { word: "inveterate", definition: "Having a habit or interest that is deeply established",     example: "He was an inveterate traveler who had visited over eighty countries." },
      { word: "lachrymose", definition: "Producing or prone to tears",                               example: "The lachrymose ending was criticized for being manipulative rather than genuinely moving." },
      { word: "mellifluous", definition: "Having a pleasant, smooth, rich sound",                    example: "The narrator's mellifluous voice made the documentary easy to listen to for hours." },
      { word: "neologism",  definition: "A newly coined word or phrase",                             example: "Ghosting is a neologism that describes ending a relationship by simply disappearing." },
      { word: "obfuscate",  definition: "To make something unclear or confusing on purpose",         example: "The dense legal language was designed to obfuscate rather than clarify." },
      { word: "palimpsest", definition: "Something with evidence of many layers or stages of history", example: "The city is a palimpsest — every era has left its mark on the architecture." },
      { word: "recalcitrant", definition: "Having an obstinately uncooperative attitude",            example: "The recalcitrant defendant refused to answer any questions put to him." },
      { word: "sesquipedalian", definition: "Using very long words",                                 example: "His sesquipedalian vocabulary made his emails difficult to read." },
      { word: "tautology",  definition: "Saying the same thing twice in different words; unnecessary repetition", example: "'A free gift' is a tautology because a gift is by definition free." },
      { word: "truculent",  definition: "Eager to argue or fight; aggressively defiant",             example: "The truculent attorney questioned the judge's impartiality in open court." },
      { word: "vacuous",    definition: "Having or showing a lack of thought or intelligence",       example: "The op-ed was criticized as vacuous — full of words but completely lacking substance." },
      { word: "vitriolic",  definition: "Cruel and bitter in speech or writing",                     example: "The vitriolic article attacked the artist's character rather than her work." },
      { word: "zenith",     definition: "The highest point; the peak",                               example: "The empire was at its zenith at the turn of the century." }
    ],
    wordsmith: [
      { word: "adumbrate",  definition: "To outline or indicate in a general way; to foreshadow",    example: "The opening chapter adumbrates the themes of betrayal that dominate the novel." },
      { word: "circumlocution", definition: "The use of many words where fewer would do; evasive talk", example: "His ten-minute response was pure circumlocution — he never actually answered the question." },
      { word: "enervate",   definition: "To make someone feel drained of energy or vitality",        example: "The oppressive heat enervated the whole team within an hour of the match starting." },
      { word: "grandiloquent", definition: "Pompous and extravagant in language",                    example: "His grandiloquent speech impressed no one — it was all style and no substance." },
      { word: "harbinger",  definition: "A person or thing that announces or signals what is to come", example: "The first robin is often seen as a harbinger of spring." },
      { word: "lachrymose", definition: "Tearful or given to weeping; overly sentimental",          example: "The final chapter was so lachrymose that it felt more melodramatic than moving." },
      { word: "mellifluous", definition: "Sweet or musical; smooth and rich sounding",              example: "Her mellifluous voice made even a dry weather report sound pleasant." },
      { word: "neologism",  definition: "A new word or expression that has entered common use",      example: "Words like 'selfie' and 'vlog' are neologisms born in the digital age." },
      { word: "obfuscate",  definition: "To render obscure, unclear, or unintelligible deliberately", example: "The politician's answer seemed designed to obfuscate rather than explain." },
      { word: "palimpsest", definition: "Something reused or altered but still bearing traces of its earlier form", example: "The modern building's facade is a palimpsest — you can still see the old brickwork beneath." },
      { word: "recondite",  definition: "Not known by many; obscure or esoteric",                   example: "His lecture on recondite medieval manuscripts attracted only a dozen specialists." },
      { word: "sesquipedalian", definition: "Characterized by the use of excessively long words",   example: "The professor's sesquipedalian writing style alienated readers outside the field." },
      { word: "tautology",  definition: "Saying the same thing twice with different words",          example: "The phrase 'end result' is a tautology since 'end' and 'result' already mean the same thing." },
      { word: "umbrage",    definition: "Offense or displeasure taken at something",                 example: "She took great umbrage at being left off the invitation list." },
      { word: "verisimilitude", definition: "The appearance of being true or real",                  example: "The novel's verisimilitude depended on the author's deep research into the period." },
      { word: "vitiate",    definition: "To impair or make faulty; to destroy the legal validity of", example: "The discovery of forged signatures threatened to vitiate the entire agreement." },
      { word: "heuristic",  definition: "Enabling discovery through trial and error rather than a fixed formula", example: "Good teachers use heuristic methods that encourage students to explore rather than memorize." },
      { word: "apocryphal", definition: "Of doubtful authenticity; widely circulated but probably not true", example: "The story about Napoleon's height is largely apocryphal." },
      { word: "tendentious", definition: "Promoting a particular cause or point of view; biased",   example: "The report was criticized for its tendentious presentation of the data." },
      { word: "liminal",    definition: "Relating to a transitional or initial stage; occupying a threshold", example: "Adolescence is a liminal period between childhood and adulthood." }
    ]
  },

  /* ══════════════ GRADE 10 ══════════════ */
  grade10: {
    novice: [
      { word: "abeyance",   definition: "A state of temporary suspension or inactivity",             example: "Development of the project was held in abeyance while funding was secured." },
      { word: "circumspect", definition: "Thinking carefully about all circumstances before acting", example: "Politicians must be circumspect in what they say publicly." },
      { word: "debilitate", definition: "To make someone very weak or unable to function normally",  example: "The injury debilitated the athlete for months." },
      { word: "enervate",   definition: "To drain someone's energy or strength",                     example: "The long, uneventful meeting enervated everyone in the room." },
      { word: "fulsome",    definition: "Excessively complimentary, often to the point of being insincere", example: "The fulsome praise made the recipient uncomfortable." },
      { word: "grandiloquent", definition: "Using very grand, pompous language",                     example: "His grandiloquent acceptance speech was three times longer than necessary." },
      { word: "harbinger",  definition: "A forerunner; something that announces what is to come",    example: "The first frost is a harbinger of the winter ahead." },
      { word: "imperious",  definition: "Arrogantly expecting obedience or deference",              example: "Her imperious manner made it impossible to disagree with her." },
      { word: "jettison",   definition: "To throw away or abandon something no longer needed",       example: "The startup decided to jettison its original model in favor of a subscription service." },
      { word: "lachrymose", definition: "Tearful; tending to cry",                                   example: "The lachrymose tribute moved several audience members to tears." },
      { word: "mellifluous", definition: "Sweetly and smoothly flowing; pleasing to hear",           example: "The speaker's mellifluous baritone made every word easy to follow." },
      { word: "nefarious",  definition: "Wicked; criminal; involving serious wrongdoing",            example: "The court documents described a decade of nefarious financial conduct." },
      { word: "obstreperous", definition: "Noisy and hard to control",                               example: "The obstreperous protesters drowned out the speaker entirely." },
      { word: "perfidious", definition: "Deceitful and untrustworthy; treacherous",                 example: "The perfidious adviser had been feeding secrets to rivals for years." },
      { word: "querulous",  definition: "Complaining in an irritable and petulant way",              example: "His querulous emails arrived daily, always finding fault." },
      { word: "recondite",  definition: "Dealing with obscure subject matter; known by few",         example: "Her expertise in recondite areas of tax law made her indispensable." },
      { word: "sagacious",  definition: "Having good judgment; shrewd and wise",                     example: "The sagacious investor saw the market crash coming months before it happened." },
      { word: "tendentious", definition: "Promoting a particular viewpoint; biased",                 example: "The documentary was criticized for its tendentious framing of the events." },
      { word: "umbrage",    definition: "Offense; resentment",                                       example: "He took umbrage at being described as a minor player in the deal." },
      { word: "vitiate",    definition: "To spoil or impair the quality of; to make invalid",        example: "The newly discovered flaw could vitiate the entire argument." }
    ],
    sleuth: [
      { word: "adumbrate",  definition: "To present in a shadowy outline; to foreshadow",            example: "The early scenes adumbrate the tragedy that follows without giving it away." },
      { word: "bellwether", definition: "An indicator of future trends; a leading figure",           example: "The bellwether county always votes in line with the eventual winner." },
      { word: "circumlocution", definition: "Evasive or unnecessarily wordy language",              example: "He answered in circumlocution, somehow managing to avoid every direct question." },
      { word: "deracinate", definition: "To pull up by the roots; to displace someone from their culture", example: "The policy effectively deracinated entire communities from their ancestral lands." },
      { word: "ephemeral",  definition: "Short-lived; transitory",                                   example: "Fame in the age of social media is often ephemeral — here today, forgotten in a week." },
      { word: "festoon",    definition: "To decorate with chains or garlands; to overly adorn",      example: "The hall was festooned with flowers and ribbons for the graduation ceremony." },
      { word: "garrulous",  definition: "Excessively talkative, especially on trivial matters",     example: "His garrulous storytelling stretched a two-minute anecdote into twenty." },
      { word: "inveterate", definition: "Long-established and unlikely to change",                   example: "An inveterate pessimist, she prepared for the worst no matter how promising things looked." },
      { word: "juxtapose",  definition: "To place contrasting things side by side for effect",      example: "The novelist juxtaposes opulent banquets with scenes of starvation." },
      { word: "lachrymose", definition: "Tearful; inducing tears",                                   example: "The lachrymose score underscored every scene of loss in the film." },
      { word: "mendacious", definition: "Given to lying; untruthful",                               example: "The mendacious memoir was later revealed to contain numerous fabricated events." },
      { word: "neologism",  definition: "A newly coined word or expression",                         example: "The pace at which digital life generates neologisms has accelerated dramatically." },
      { word: "obfuscate",  definition: "To deliberately make unclear or confusing",                 example: "Dense legal prose is often used to obfuscate rather than inform." },
      { word: "palimpsest", definition: "An object or text that carries layers of earlier history",  example: "The city's underground railway is a palimpsest of a dozen different engineering eras." },
      { word: "recalcitrant", definition: "Obstinately resistant to authority or direction",         example: "The recalcitrant nation refused to comply with international sanctions." },
      { word: "sesquipedalian", definition: "Given to using very long words",                        example: "His sesquipedalian prose was admired by scholars and avoided by everyone else." },
      { word: "tautology",  definition: "Needless repetition of the same idea in different words",   example: "The phrase 'future plans' is a tautology — plans are inherently about the future." },
      { word: "umbrage",    definition: "Offense or annoyance at a perceived slight",               example: "The ambassador took umbrage at the way the summit ignored her delegation." },
      { word: "vestige",    definition: "A trace of something that is disappearing",                 example: "Only a vestige of the original garden remained after decades of neglect." },
      { word: "zeitgeist",  definition: "The defining spirit or mood of a historical period",        example: "The novel captured the zeitgeist of the post-war decade with remarkable precision." }
    ],
    wordsmith: [
      { word: "anachronism", definition: "A thing or person belonging to a different time",         example: "The anachronism of a smartphone in a period drama broke the audience's immersion." },
      { word: "apocryphal", definition: "Of questionable authenticity; widely repeated but unverified", example: "The famous quote is almost certainly apocryphal — no primary source has ever been found." },
      { word: "byzantine",  definition: "Excessively complicated or intricate",                      example: "The byzantine regulations governing the sector deter most new entrants." },
      { word: "circumlocution", definition: "The use of many words to say what could be said in few", example: "His answer was a masterpiece of circumlocution that avoided every direct claim." },
      { word: "encomium",   definition: "A formal speech or piece of writing praising someone",      example: "The encomium delivered at the ceremony brought the honoree to tears." },
      { word: "grandiloquent", definition: "Using inflated, pompous language to impress",            example: "His grandiloquent manifesto promised everything and specified nothing." },
      { word: "heretical",  definition: "Contrary to orthodoxy; unorthodox",                        example: "The economist's heretical predictions were dismissed in 2005 and vindicated in 2008." },
      { word: "iconoclast", definition: "Someone who challenges long-held beliefs or institutions",  example: "She was an iconoclast in the field, overturning decades of received wisdom." },
      { word: "liminal",    definition: "Relating to a threshold; between two states",              example: "The months after graduation exist in a liminal space between student life and adulthood." },
      { word: "mellifluous", definition: "Having a smooth, rich, pleasing sound",                   example: "His mellifluous delivery transformed a difficult legal argument into something almost musical." },
      { word: "nihilism",   definition: "The philosophical view that life has no meaning or value",  example: "His nihilism made commitment to any long-term goal seem pointless to him." },
      { word: "obfuscate",  definition: "To make unclear; to confuse or bewilder",                   example: "The lengthy disclaimer seemed designed to obfuscate rather than disclose." },
      { word: "palimpsest", definition: "Anything that shows layers of history; a manuscript reused but still bearing earlier text", example: "The scholar treated the amended constitution as a palimpsest — each layer revealed political compromise." },
      { word: "quixotic",   definition: "Impractically idealistic; naively romantic in pursuit of unreachable goals", example: "The quixotic proposal to eliminate all carbon emissions within five years attracted ridicule." },
      { word: "recondite",  definition: "Little known; obscure; beyond ordinary knowledge",         example: "The jury struggled to follow the expert's testimony on recondite aspects of genetics." },
      { word: "sesquipedalian", definition: "Using or characterized by long words",                  example: "Her sesquipedalian style has made her writing admired in academic circles and unread outside them." },
      { word: "solipsism",  definition: "The view that only one's own mind is certain; extreme self-centeredness", example: "A degree of solipsism is inevitable in autobiography — the self is always the center." },
      { word: "tendentious", definition: "Expressing a particular cause with bias",                  example: "The tendentious analysis cited only studies that supported its predetermined conclusion." },
      { word: "verisimilitude", definition: "The quality of seeming to be true or real",             example: "Meticulous period details gave the film a verisimilitude that previous adaptations lacked." },
      { word: "heuristic",  definition: "A practical approach that allows discovery through exploration; an approximate solution method", example: "The algorithm uses a heuristic to find good-enough answers fast rather than perfect ones slowly." }
    ]
  }

};
